# Generated by Django 3.2.13 on 2022-12-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20221226_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('RECOMMEND', '추천·리뷰'), ('BASIC', '기초상식'), ('BODO', '보도자료'), ('YEAR', '연말정산'), ('NEWS', '뉴스'), ('ECT', '기타')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
