# Generated by Django 3.2.13 on 2022-12-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_alter_magazine_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('BODO', '보도자료'), ('BASIC', '기초상식'), ('ECT', '기타'), ('YEAR', '연말정산'), ('NEWS', '뉴스'), ('RECOMMEND', '추천·리뷰')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.comment')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.magazine')),
            ],
        ),
    ]
