# Generated by Django 3.2.13 on 2023-01-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_auto_20221229_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('NEWS', '뉴스'), ('BODO', '보도자료'), ('RECOMMEND', '추천·리뷰'), ('BASIC', '기초상식'), ('YEAR', '연말정산'), ('ECT', '기타')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
