# Generated by Django 3.2.13 on 2023-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_alter_magazine_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('BASIC', '기초상식'), ('BODO', '보도자료'), ('RECOMMEND', '추천·리뷰'), ('NEWS', '뉴스'), ('YEAR', '연말정산'), ('ECT', '기타')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
